server:
  port: 8082

spring:
  application:
    name: aegis-bff
  profiles:
    active: dev
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379

aegis:
  identity-service:
    url: http://localhost:8081
  wallet-service:
    url: http://localhost:8083
